### ISSUE TITLE
Tidal support ?

### ISSUE THREAD

**Issue by pascaltuf** [mtricht/gamesense-essentials#102]
Support for tidal because the one already integrated after a while when the tidal window is reduced to an icon it no longer works and the plugin is deactivated and to make it work again you have to keep the tidal window running on the screen every time.

**Comment by mtricht** [comment]
@pascaltuf Added in newest version, let me it know if it works to your liking: https://github.com/mtricht/gamesense-essentials/releases/tag/1.13.0

**Comment by pascaltuf** [comment]
Tomorrow I will try it on the apex pro and in that case if there are multiple devices with the screen is it reproduced on both devices or only on one at a time?

**Comment by pascaltuf** [comment]
Oh and I forgot, thank you very much for what you are doing and above all for adding support to tidal, you are a great man, I still can't believe it's working

**Comment by mtricht** [comment]
It will display on all OLED screens but you should be able to select just one somewhere in steelseries GG. Don't know exactly as I only have one.
