### ISSUE TITLE
Add inclusion for th-ch's youtube music api

### ISSUE THREAD

**Issue by ActuallyFreshIce** [mtricht/gamesense-essentials#118]
th-ch added swagger api to the youtube music app, if possible could you add this to the gamesense essentials, im already working on a fork of it that includes it btw

**Comment by ActuallyFreshIce** [comment]
Nevermind I lowkey gave up bc I cant wrap my head around it, but I know someone smarter can easily do it

**Comment by mtricht** [comment]
@ActuallyFreshIce Latest version should work: https://github.com/mtricht/gamesense-essentials/releases/tag/1.15.0
