### ISSUE TITLE
YouTube Music Support

### ISSUE THREAD

**Issue by dan23945** [mtricht/gamesense-essentials#13]
Any way to add YouTube Music support? If not possible because it doesn't have an official desktop app. Maybe it would be possible to integrate with the "YouTube Music Desktop" project's app?

https://ytmdesktop.app/
https://github.com/ytmdesktop/ytmdesktop

**Comment by mtricht** [comment]
@dan23945  It's possible but there would be one downside; after pausing in the youtube music desktop application the song information would stay on the OLED, it'd go away only after completely closing the program. is that okay?

**Comment by dan23945** [comment]
Not a problem! Thanks!

**Comment by mtricht** [comment]
@DroidBV8 Give [1.5.0](https://github.com/mtricht/gamesense-essentials/releases/download/1.5.0/gamesense-essentials-1.5.0.msi) a try!
