### ISSUE TITLE
Add support for AIMP Music Player

### ISSUE THREAD

**Issue by DroidBV8** [mtricht/gamesense-essentials#15]
Hello, 

Big thanks for your app, it's amazing.
It's possible to add a support for AIMP3 music player. 
It's a very good player and it will be amazing to see a comaptiblity with your app.

http://www.aimp.ru/

Best regards.

**Comment by mtricht** [comment]
@DroidBV8 It's possible but there would be one downside; after pausing in AIMP the song information would stay on the OLED, it'd go away only after completely closing AIMP. is that okay?

**Comment by DroidBV8** [comment]
hello,

that would be great :) 👍

**Comment by mtricht** [comment]
@DroidBV8 Give [1.5.0](https://github.com/mtricht/gamesense-essentials/releases/download/1.5.0/gamesense-essentials-1.5.0.msi) a try!
