### ISSUE TITLE
32-Bit Processors

### ISSUE THREAD

**Issue by S0ULL355** [mtricht/gamesense-essentials#16]
This does not work on or with 32 bit processors. That would be cool if it did. I know they're outdated and all but I am using a copier with a Pentium Dual Core. XDDD

**Comment by mtricht** [comment]
Lol, I'll make a release and upload a 32 bit version later tonight

**Comment by S0ULL355** [comment]
> 
> 
> Lol, I'll make a release and upload a 32 bit version later tonight

thank youuuu

**Comment by mtricht** [comment]
Can't get the volume stuff working on 32bit, might give it another try later. So for now without volume: https://github.com/mtricht/gamesense-essentials/releases/download/1.5.0/gamesense-essentials-1.5.0-x86-no-volume-slider.msi

**Comment by S0ULL355** [comment]
tbh, i just care for the spotify thing. thank you once again
