### ISSUE TITLE
tbh, i just care for the spotify thing. thank you once again

### ISSUE THREAD

**Issue by S0ULL355** [mtricht/gamesense-essentials#17]
tbh, i just care for the spotify thing. thank you once again

_Originally posted by @S0ULL355 in https://github.com/mtricht/gamesense-essentials/issues/16#issuecomment-721990804_

I cannot run it

**Comment by S0ULL355** [comment]
[https://drive.google.com/file/d/1AJeuCScE6Oer_6LUQay2CSG4BRhIL4og/view?usp=sharing](url)

**Comment by mtricht** [comment]
@S0ULL355 can you try the zip? https://github.com/mtricht/gamesense-essentials/releases/download/1.5.0/gamesense-essentials-1.5.0-x86-no-volume-slider.zip

**Comment by S0ULL355** [comment]
It does indeed work this time, sorry for being a pain about it.

**Comment by mtricht** [comment]
Great to hear and no problem
