### ISSUE TITLE
An option to disable the clock icon.

### ISSUE THREAD

**Issue by lemonnade0** [mtricht/gamesense-essentials#18]
Leaving the static clock icon on for long periods of time might cause burn in, so an option to disable it would be nice.

**Comment by mtricht** [comment]
Agreed, expect a new version this weekend

**Comment by mtricht** [comment]
@lemonnade0 see https://github.com/mtricht/gamesense-essentials/releases/tag/1.6.0

**Comment by lemonnade0** [comment]
Thanks!
