### ISSUE TITLE
When clock is disabled closing volume or music display disables the keyboard LED's for a second.

### ISSUE THREAD

**Issue by lemonnade0** [mtricht/gamesense-essentials#19]

**Comment by Dakusan03** [comment]
Hello ! I confirm this issue. All the LED turn off and on before going back to the normal configuration with the gif. Otherwise thanks a lot for your time on this tool, it's awesome and was really needed !

**Comment by Ded-Ex** [comment]
I'm encountering the issue as well, and it's really frustrating considering how great the rest of it works. Hope this can be fixed soon. @mtricht

**Comment by mtricht** [comment]
That's just how the gamesense SDK works. It's either this or the music display 'frozen' until you play something again. What'd you prefer?

**Comment by Ded-Ex** [comment]
Ah that's unfortunate, guess I'll just stick with it for now.

Thanks for responding anyway and I think that sorts it.
