### ISSUE TITLE
Add non-latin symbols support

### ISSUE THREAD

**Issue by LemonJuicer** [mtricht/gamesense-essentials#21]
I don't know about others, but japanese symbols are not being displayed.

**Comment by mtricht** [comment]
Sadly not much I can do about: https://github.com/SteelSeries/gamesense-sdk/issues/78#issuecomment-606698348

**Comment by LemonJuicer** [comment]
Well, I tried(

**Comment by kvalle22** [comment]
It's working now! 
![image](https://github.com/mtricht/gamesense-essentials/assets/26128231/bd2bcd7f-3d8f-43e2-b6ab-fd136fa5300c)
