### ISSUE TITLE
Buttons not working while music is being played

### ISSUE THREAD

**Issue by LemonJuicer** [mtricht/gamesense-essentials#22]
Can't close music display and use menu.

Solution: add exit function on small button.
Suggestion: add music controls (skip, pause)
Device: Arctis Pro Wireless

**Comment by LemonJuicer** [comment]
How I would do it:
![Untitled-1](https://user-images.githubusercontent.com/64481039/104814554-e2566a80-580f-11eb-9934-136fd2b26600.png)
![Untitled-2](https://user-images.githubusercontent.com/64481039/104814559-e4202e00-580f-11eb-96a1-6d3f2281e229.png)

**Comment by LemonJuicer** [comment]
Another good solution would be to show it like screensaver like I said in issue #23

**Comment by mtricht** [comment]
@LemonJuicer What the buttons do is all in steelseries hands, can't do anything with them
