### ISSUE TITLE
Screen glitch

### ISSUE THREAD

**Issue by LemonJuicer** [mtricht/gamesense-essentials#23]
I was called while listening to music
![945a52b3-38b3-4f15-9591-d14fe92cad0b](https://user-images.githubusercontent.com/64481039/104814804-036b8b00-5811-11eb-98dc-fa8e7d101ab9.jpg)
Solution: show music screen like screensaver if API allows to do so.

**Comment by mtricht** [comment]
@LemonJuicer Is this another app (that shows caller information) thats clashing with gamesense essentials? I don't think I can do anything about this, you'd have to close gamesense essentials when you get called I'm afraid

**Comment by LemonJuicer** [comment]
I turned off everything a had but it still was happening sometimes. Asked for replacement for other reasons but seems like it solved the problem
