### ISSUE TITLE
High CPU load

### ISSUE THREAD

**Issue by LemonJuicer** [mtricht/gamesense-essentials#24]
task manager shows usage from 4 to 9 percent!

CPU: Ryzen 3 2200g

**Comment by LemonJuicer** [comment]
![image](https://user-images.githubusercontent.com/64481039/104839814-fc518500-58c3-11eb-8336-d3ee043aef4e.png)
when music is playing load is around 2%, but when music stops it uses way more

**Comment by mtricht** [comment]
You should probably increase the ticktrate

**Comment by LemonJuicer** [comment]
That was stupid -_-
