### ISSUE TITLE
Selective screens?

### ISSUE THREAD

**Issue by SilverAura** [mtricht/gamesense-essentials#34]
I've got both an Apex 7 and the Arctis Pro Wireless. I was curious if there was or could have added support for choosing what display gets what, if anything, as well as the ability to disable the icon. Basically, similar functionality to the Engine Software.

**Comment by mtricht** [comment]
Hi @SilverAura,

I can not decide on what screen my app gets displayed. You have to configure that through the steelseries engine. So open the engine, go to apps, open GAMESENSE_ESSENTIALS and you should be able to configure it there.

As for the ability to disable the icon: download the latest version, which has an option for this https://github.com/mtricht/gamesense-essentials/releases/tag/1.6.0
