### ISSUE TITLE
changing the download file for dummies

### ISSUE THREAD

**Issue by VolkisVY9** [mtricht/gamesense-essentials#35]
I downloaded gamesense-essentials, but want the song and artist name flipped. I know that there is a code that changes this, but i don't know how to make use of it. 
Can someone please help and explain how i should do that?
I'm sorry for such a dumb question.

**Comment by mtricht** [comment]
Here's a release with that included: https://github.com/mtricht/gamesense-essentials/releases/tag/1.7.0
