### ISSUE TITLE
The App Isn't Opening

### ISSUE THREAD

**Issue by YaBoiiChaan** [mtricht/gamesense-essentials#36]
I just switched my system and I wanted to download the app again but now it's just not launching. It doesn't appear on the steelseries engine and when I try to launch it, nothing happens. How can I fix this?

**Comment by mtricht** [comment]
@YaBoiiChaan What drive is steelseries engine installed on? Currently it only works if steelseries engine is installed op the C drive

**Comment by YaBoiiChaan** [comment]
> @YaBoiiChaan What drive is steelseries engine installed on? Currently it only works if steelseries engine is installed op the C drive

It is installed on my C drive. (C:\Program Files\SteelSeries\SteelSeries Engine 3\)

I have tried reinstalling Steelseries GG as well, but that also didn't work.
