### ISSUE TITLE
foobar2000 support

### ISSUE THREAD

**Issue by mtricht** [mtricht/gamesense-essentials#4]

**Comment by qrenz** [comment]
this would be so incredible

**Comment by Bestfast** [comment]
I agree, support for foobar would be good. You can always make use of https://skipyrich.com/wiki/Foobar2000:Now_Playing_Simple to export everything you need in a .txt

**Comment by mtricht** [comment]
@Bestfast @qrenz Added support for foobar2000 in 1.9.0
