### ISSUE TITLE
Support for characters outside the Latin alphabet

### ISSUE THREAD

**Issue by kokoropaint** [mtricht/gamesense-essentials#40]
I listen to a lot of Korean/Japanese music with unromanized titles, and they show up blank when using this tool. Is there any way to add support for these character sets or is it outside of the realm of the GameSense SDK?

[Example](https://i.imgur.com/R0CneD1.png) (The song's title is entirely in Japanese and doesn't display at all)

**Comment by mtricht** [comment]
Sadly not supported by steelseries: https://github.com/mtricht/gamesense-essentials/issues/21
