### ISSUE TITLE
MacOS Version Support Broken

### ISSUE THREAD

**Issue by Philbeey** [mtricht/gamesense-essentials#42]
Version 1.3.0 the only one with a Mac .dmg is currently broken and gives an error
![Screen Shot 2021-09-28 at 11 22 11 am](https://user-images.githubusercontent.com/91553659/135116915-1bd15adf-4ff7-4cf7-b9c2-6f4054af8dec.png)

Will MacOS support continue or is this a strictly Windows project from this point on.

*Thanks for the hard work though!*

**Comment by mtricht** [comment]
I no longer own a MacBook so from now on only Windows sadly
