### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by ClementYziquel5** [mtricht/gamesense-essentials#46]
Hi, does it works with Windows 11? 

I downloaded the file, executed and put it in C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup

Maybe there is somethig else to do?

Thanks

**Comment by Liquidmasl** [comment]
Works flawlessly for me, so its not win 11

**Comment by mtricht** [comment]
@Cl3ment56 Did you run the installation wizard and place the shortcut icon in the startup folder?
