### ISSUE TITLE
Stops working after the computer goes to sleep

### ISSUE THREAD

**Issue by Nahor** [mtricht/gamesense-essentials#47]
When the computer wakes up after going to sleep, the app stops updating the OLED display. The keyboard just shows the standard "SteelSeries" logo instead.

Opening the tick rate window and clicking "Ok", i.e. re-applying the same tick rate, is enough to fix the issue (until the next sleep that is)

**Comment by Nahor** [comment]
Hmm, there might be a timing issue as well. When I woke my computer this morning, the display was working fine.

Although... the keyboard illumination/color led were not working, so maybe something didn't reset correctly, which might be what allowed gamesense-essentials to keep working?

**Comment by Nahor** [comment]
Just got an update for SteelSeries GG which might shed some light on the issue: after GG restarted, gamesense was not working.
That said, in this case, re-applying the tick rate didn't restore the functionality. I had to restart gamesense instead. So it might be a different issue.

**Comment by mtricht** [comment]
@Nahor Thanks for the detailed report, I believe the two issues you describe are one and the same. It doesn't always happen when waking up because it's a timing issue (a race condition).

I handle failures when talkin to Steelseries GG more graciously now and gamesense essentials should 'reconnect' itself when this occurs.

**Comment by Nahor** [comment]
@mtricht It doesn't seem to be fixed, or there is another similar one. I could reproduce with 1.8 when checking the 24h clock fix. When the clock is moved backward, everything freezes and gets reset (issue #50). After the reset, the display shows the SteelSeries logo instead of gamesense. The quick fix of re-applying the tick rate solves it.

**Comment by mtricht** [comment]
@Nahor A better way to test this would be to completely close Steelseries GG whilst gamesense essentials is running. After opening GG again, it should automatically reconnect.

I think moving the clock back isn't a realistic scenario outside DST

**Comment by Nahor** [comment]
Moving the clock backward was not meant as a way to test this particular issue (*). It just that I was testing the clock and noticed gamesense not working anymore. But I do not know if it is the same issue indeed, or just gamesense not even trying to reconnect because of the separate clock problem.
For this issue, yes restarting GG seems to work (I never tried that before though, beside that one GG update). I haven't tried putting my computer to sleep yet, I'll be necessarily testing that over the next few days anyway :)

(*) I would say though that assuming the clock won't be change outside DST is misguided. Making assumption on how people use their computer is one source of bugs. In this case, maybe a developer is writing a task scheduler, or a tester is testing a calendar, or someone is connected to a broken NTP server. Who knows.

**Comment by mtricht** [comment]
@Nahor Have you had any more issues since the last update?

**Comment by Nahor** [comment]
I did. Every now and then, after a wakeup, gamesense won't reconnect, but it's rare (less than a handful of times so far).
