### ISSUE TITLE
Support for 24h clock format

### ISSUE THREAD

**Issue by Nahor** [mtricht/gamesense-essentials#48]
Most of the world use the 24h clock format. It would be nice to have that available in the tool.

**Comment by mtricht** [comment]
@Nahor This is tied to your windows's locale, is your windows by chance set to a locale that uses a 12h clock format?

**Comment by Nahor** [comment]
@mtricht It's kind of both. The pure locale is 12h clocks (US format), but I changed the "Region settings" so that Windows uses 24h clock (systray clock, Windows explorer, ...).

So it looks like gamesense-essentials uses the "pure locale" instead of Windows regional format.

**Comment by mtricht** [comment]
@Nahor Thanks for the clarification. Sadly even then I'm unable to reproduce. I tested with the language/country set to US and region format to Dutch. What is your region format set to?

**Comment by Nahor** [comment]
Here is my region settings:
> ![image](https://user-images.githubusercontent.com/1198364/145433694-206585c2-ddee-41ab-af51-0f5efbfc8325.png)

and the customized settings:
> ![image](https://user-images.githubusercontent.com/1198364/145433644-6041e82c-af94-4ee1-a86d-5afbff883344.png)

**Comment by mtricht** [comment]
@Nahor This is now fixed in 1.8.0!
