### ISSUE TITLE
Gamesense-essentials stops working when the clock is moved backward

### ISSUE THREAD

**Issue by Nahor** [mtricht/gamesense-essentials#50]
When the clock is moved backward (I was testing the 24h clock fix, but I suspect this will also apply for changes like daylight savings), the display stops updating for a short time, then the whole keyboard/GG restarts.

My assumption is that gamesense blocks while waiting for the next tick or something like that, and GG resets because the tool is now unresponsive.

**Comment by mtricht** [comment]
This is a bug in the JDK: https://bugs.openjdk.java.net/browse/JDK-4290274

I'd have to use something else than Java's `TimerTask` but this is a rather small edge case that should only happen during DST
