### ISSUE TITLE
Steelseries GG shows the app but the app isn't working

### ISSUE THREAD

**Issue by nevergonnagive** [mtricht/gamesense-essentials#53]
Hi I just installed the app and although I can see and enable it on the Steelseries Engine it doesn't work. How can I fix it? The app and Steelseris GG are iboth nstalled on C:/Program Files

**Comment by mtricht** [comment]
Is it running? Do you see gamesense essentials in your system tray? It's the green check mark:
![image](https://user-images.githubusercontent.com/7511094/150866424-9bc3b138-29da-4c54-b3d8-45aea8d0992c.png)

**Comment by nevergonnagive** [comment]
Yeah, it is running and I can activate it on the app but it doesn't work. Idk if it has anything to do with the app, but my Java seems to be broken. I can't run any software using Java and my .jar files won't open. As I said I don't know if it has anything to do with this issue but maybe it does.
