### ISSUE TITLE
All of a sudden today the app won't open

### ISSUE THREAD

**Issue by Big-Barry** [mtricht/gamesense-essentials#57]
Even after a reinstall

**Comment by wik3d** [comment]
Same issue here, nothing changed but it will not open anymore

**Comment by Big-Barry** [comment]
Is there an alternative to this since this program was hella useful for my gamedac

**Comment by mtricht** [comment]
Works on my machine™

You could try reinstalling steelseries GG engine and making sure the `C:\ProgramData\SteelSeries\GG` folder is completely deleted (you will lose all settings unless they're saved on the device(s))
