### ISSUE TITLE
Shows the same info on several OLEDs

### ISSUE THREAD

**Issue by Seksullah** [mtricht/gamesense-essentials#63]
Hello, i both have Apex Pro and Arctis Pro Wireless. Both of them has OLED displays. This app shows info on both of the screens and i want to have System info on my arctis and have the music info only on my keyboard. Is this possible to do and if how?

**Comment by mtricht** [comment]
@Seksullah You can configure this inside Steelseries GG somewhere under Engine -> Apps -> Gamesense Essentials. I don't have more than one screen so I don't know but there are people who have found this
