### ISSUE TITLE
gamesense-essentials seems to be broken after Windows 11 22H2 update

### ISSUE THREAD

**Issue by chidi9901** [mtricht/gamesense-essentials#64]
I am not 100% sure if it's caused by the newest Windows update or by an also recent update of the SteelSeries GG suite to version 24.0.0. Anyways, restarting gamesense crashes or freezes the keyboard for a second and then when it's unfrozen, the OLED shows default picture.

**Comment by mtricht** [comment]
No issues here, try reinstalling both GG and GE

**Comment by KNEWIGVB** [comment]
Same issue here. Not working after 22H2 update.
Uninstalled/reinstalled both. 
If I change the tick rate higher than 200ms, it works for 5 seconds, than stops working again.

**Comment by KNEWIGVB** [comment]
**UPDATE:**
I have tried the older versions and looks like **v1.5.0** and OLDER versions work.
v1.6.0 and NEWER ones stop al working after 5 seconds.

**Comment by chidi9901** [comment]
> **UPDATE:** I have tried the older versions and looks like **v1.5.0** and OLDER versions work. v1.6.0 and NEWER ones all stopped working after 5 seconds.

That's interesting. I'm wondering if the developer could look in to that, and we shall get a v2.00 or something.

**Comment by mtricht** [comment]
@chidi9901 @KNEWIGVB Can you give https://github.com/mtricht/gamesense-essentials/releases/tag/1.10.0 a try?

**Comment by chidi9901** [comment]
> @chidi9901 @KNEWIGVB Can you give https://github.com/mtricht/gamesense-essentials/releases/tag/1.10.0 a try?

Thanks, it's fixed and working perfectly now!

**Comment by chidi9901** [comment]
> @chidi9901 @KNEWIGVB Can you give https://github.com/mtricht/gamesense-essentials/releases/tag/1.10.0 a try?

Thanks, it's fixed and working perfectly now!
