### ISSUE TITLE
Current Song Not Displaying - Spotify Desktop app

### ISSUE THREAD

**Issue by l-Xevia-l** [mtricht/gamesense-essentials#67]
After installation, everything but the song stats (the whole reason I downloaded this) is working. I can change the clock and tickspeed, and the volume slider works. But nothing happens when I play a song.

**Comment by mtricht** [comment]
@l-Xevia-l No issues here, what OS version are you on and what steelseries device do you use?

**Comment by l-Xevia-l** [comment]
Apex 7, and I'm on the latest version of Win10.

**Comment by l-Xevia-l** [comment]
> @l-Xevia-l No issues here, what OS version are you on and what steelseries device do you use?

Apex 7, and I'm on the latest version of Win10.

**Comment by l-Xevia-l** [comment]
@mtricht Would it be helpful for me to attach my system specs?

**Comment by mtricht** [comment]
@l-Xevia-l No, that's not necessray. When you play a song on spotify, do you see the artist and song when you hover over spotify on the task bar like this?
![image](https://user-images.githubusercontent.com/7511094/210135024-7a7e57ca-0bee-46eb-9cb1-10296841850b.png)

**Comment by l-Xevia-l** [comment]
@mtricht I do not see it the way it is supposed to be, i.e. it shows the preview like any other window.

FYI, I am using custom icons, which really shouldn't logically affect that, but I'm not sure.

**Comment by l-Xevia-l** [comment]
@mtricht Would Uninstall-Reinstall help? 

I probably should've tried that already...

**Comment by l-Xevia-l** [comment]
@mtricht I've tried uninstalling and reinstalling multiple times and done all the troubleshooting I really know short of looking at the source code myself.

Is there anything else I can do/help you do? I understand that this isn't your main priority in life, and are in no way obliged to help, but If you do have any extra time that you want to commit to this I would greatly appreciate it!

**Comment by mtricht** [comment]
@l-Xevia-l I tested it on windows 10 and no issues there. What language is your windows on?

Can you make a screenshot and upload it like the one in my previous post showing the spotify window with the artist and song name?

Could you also try one of the other players, such as the youtube music app that I link to in the README?

**Comment by mtricht** [comment]
@l-Xevia-l How does the gamesense essential app look like in your Steelseries GG? Can you make a screenshot like mine below to see if there are any differences?

![image](https://user-images.githubusercontent.com/7511094/211926348-98be4aba-2fe3-4064-866e-f09a36d9a296.png)

**Comment by l-Xevia-l** [comment]
@mtricht Oddly enough, It JUST started working... I had the idea that the Spotify app I was using *could* be the wrong one. SO I looked up the Spotify app on the Windows store and downloaded it and used it instead of the online download from Spotify, inc.

Sorry for wasting your time and have a wonderful day!
