### ISSUE TITLE
overtakes pro wireless box

### ISSUE THREAD

**Issue by Hamburgalarr** [mtricht/gamesense-essentials#68]
The oled screen on the pro wireless box is overtaken by game essentials and wont display any other information, no option to turn it off  so it only displays on apex 7

**Comment by mtricht** [comment]
You can select in steelseries GG which screen to display it on

**Comment by Hamburgalarr** [comment]
I hate to be a noob but how it doesnt show up in Apps

**Comment by Hamburgalarr** [comment]
Never mind found it, thank you, im a idiot

**Comment by mtricht** [comment]
Could you post a screenshot of how it looks? Just so I can post it for the next person :) I no longer have anything from steelseries

**Comment by Hamburgalarr** [comment]
<img width="1241" alt="Screenshot 2023-01-10 194524" src="https://user-images.githubusercontent.com/76851188/211647747-9cb1eaca-4a0b-4b40-ba3a-b860d42026fc.png">

**Comment by Hamburgalarr** [comment]
<img width="1252" alt="Screenshot 2023-01-10 194634" src="https://user-images.githubusercontent.com/76851188/211647924-abd0eea9-fa87-4018-813a-910998591787.png">

**Comment by mtricht** [comment]
Thank you!
