### ISSUE TITLE
Not recognized at startup

### ISSUE THREAD

**Issue by langestefan** [mtricht/gamesense-essentials#72]
I have put the gamesense-essentials shortcut in the startup folder as the instructions said. The app also successfully starts up and I can see it in the system tray. However it doesn't activate unless I manually restart the app. 

Perhaps it's starting too fast, before the steelseries app? And therefore it is not recognized at startup?

**Comment by mtricht** [comment]
If it starts before steelseries GG it keeps trying until it has started, so that shouldn't be it.
Sadly it works on my machine™. Using latest version of steelseris GG and gamesense essentials? Using Windows 11?

**Comment by langestefan** [comment]
It's not picking it up for some reason though. If I go into the steelseries GG tool it shows it's not being controlled until I restart gamesense.

> Using latest version of steelseris GG and gamesense essentials? Using Windows 11?

Yep, I just got the Apex 7 a few days ago so that's when I installed everything. On Windows 11.

**Comment by langestefan** [comment]
@mtricht any update? It's still not working.

**Comment by mtricht** [comment]
I tried again today and I have been unable to reproduce it sadly.

Could one of you @ChrisvanChip @langestefan replace the gamesense-essentials shortcut in the startup folder with the following batch script?
Create a file named `gamesense-essentials.bat` with:
```bat
cd "%LOCALAPPDATA%\gamesense-essentials"
runtime\bin\java.exe -Djava.locale.providers=HOST -cp app\* dev.tricht.gamesense.MainKt
```

On startup you'll see the program running in a command prompt like so:
![image](https://github.com/mtricht/gamesense-essentials/assets/7511094/812929bc-b4bb-4f93-947f-8177a1c37ffc)
I'm curious as to what output you guys get.

**Comment by langestefan** [comment]
Thanks for looking into it!

I got this output:

```
C:\Windows\System32>cd "C:\Users\lange\AppData\Local\gamesense-essentials"

C:\Users\lange\AppData\Local\gamesense-essentials>runtime\bin\java.exe -Djava.locale.providers=HOST -cp app\* dev.tricht.gamesense.MainKt
Exception in thread "main" java.lang.RuntimeException: IMMDeviceEnumerator::GetDefaultAudioEndpoint() failed
        at dev.tricht.gamesense.SoundUtil.Initialize(SoundUtil.java:57)
        at dev.tricht.gamesense.events.WindowsDataFetcher.<init>(WindowsDataFetcher.kt:29)
        at dev.tricht.gamesense.events.EventProducer.<init>(EventProducer.kt:14)
        at dev.tricht.gamesense.Main$Companion.startTimer(Main.kt:165)
        at dev.tricht.gamesense.MainKt.main(Main.kt:25)
        at dev.tricht.gamesense.MainKt.main(Main.kt)
```

Not sure why it's looking for an audio endpoint...?

**Comment by mtricht** [comment]
@langestefan because we show the volume level when you change it. See: https://user-images.githubusercontent.com/7511094/122837368-3e0fad00-d2f4-11eb-868e-980b2b29e1c1.mp4 ~2 seconds in

I'll try to fix it, thanks for following up.

**Comment by langestefan** [comment]
Ah ofcourse... it makes sense now. This probably won't affect many users but would be great if it can be fixed

**Comment by mtricht** [comment]
@langestefan @ChrisvanChip can you guys give this version a try? https://github.com/mtricht/gamesense-essentials/releases/tag/1.11.1
