### ISSUE TITLE
Apple Music Preview support?

### ISSUE THREAD

**Issue by ShibeGG1** [mtricht/gamesense-essentials#73]
Is it possible to add the song viewing thing on the screen to the new apple music preview on windows? thanks.

**Comment by mtricht** [comment]
@Tahuwa @ShibeGG1 I don't see a windows client for Apple Music, just a web player and through iTunes, is that correct? If so, web player is a no-go to support and iTunes is already supported.

**Comment by Tahuwa** [comment]
Hi @mtricht ,

There is indeed an Apple Music windows client, but it's only available through the Microsoft store as found here: https://apps.microsoft.com/detail/9pfhdd62mxs1?hl=en-US&gl=US

While I understand iTunes is already supported, it is pretty much missing a majority of Apple Music streaming features, hence a lot of people have switched to the native Apple Music app.

**Comment by mtricht** [comment]
I took a look and it seems like I can't support it sadly. No COM bridge like iTunes or the current song information in the window title (which is how the rest works).

**Comment by olliemaller** [comment]
Hey @mtricht 
Just thought id share this, It is called music presence and it bassiclly makes what your listning to on apple music  show up on your presence on discord like the native spotify intergration. Just was wondering if it is not possible to add apple music
https://musicpresence.app
https://github.com/ungive/discord-music-presence
