### ISSUE TITLE
Screen freezes after turning off clock and music

### ISSUE THREAD

**Issue by UDIA-GOD** [mtricht/gamesense-essentials#75]
Screen stays instead of changing to previous animation.

**Comment by mtricht** [comment]
Only one app can use the screen at a time, so you can't get the animation while using gamesense essentials.
If you disable both the clock and music I'm not sure why you'd want to use this program at all?

**Comment by UDIA-GOD** [comment]
i keep music and volume but the clock is just annoying

**Comment by UDIA-GOD** [comment]
but im saying
