### ISSUE TITLE
Is there any way to add support for Japanese and Korean characters? 

### ISSUE THREAD

**Issue by kvalle22** [mtricht/gamesense-essentials#78]
As I said in the title I was wondering if it's possible to have Japanese and Korean characters on the screen, btw great tool! Added screenshot for better understanding of the request
![image](https://github.com/mtricht/gamesense-essentials/assets/26128231/0edbd4f7-bc1d-4e4b-b65f-58e4bd6724bf)

**Comment by mtricht** [comment]
See https://github.com/mtricht/gamesense-essentials/issues/21

**Comment by kvalle22** [comment]
Understood thanks

**Comment by bsong0** [comment]
Update: Steelseries has supported utf-8. This repo can now display song name contains Chinese, etc. characters.

**Comment by kvalle22** [comment]
![image](https://github.com/mtricht/gamesense-essentials/assets/26128231/ba52575f-9e6c-4f0b-9dc5-e7d84ef3b6d5)
Awesome!
