### ISSUE TITLE
Song icon uses valuable real estate

### ISSUE THREAD

**Issue by SuperSteef** [mtricht/gamesense-essentials#80]
Love the tool but I noticed the song icon (music note) takes about 9 characters worth of space from the song title and artist names.

I was able to modify the program to remove the icon and expand the usable space and it runs successfully via IntelliJ but I don't have the experience fold it into the rest of the program.

A toggle like you have for the clock icon I think would be great to switch between the song icon and giving more space for those who prefer that.

I would love to work with one of the contributors on doing that if someone is able to show me the ropes.

Thanks!
Steef

**Comment by mtricht** [comment]
Thanks!

**Comment by mtricht** [comment]
@SuperSteef Just released 1.12.0 with your changes
