### ISSUE TITLE
accidentally deleted the display options for clock

### ISSUE THREAD

**Issue by Haque13** [mtricht/gamesense-essentials#82]
I accidentally deleted the display options for the clock.. and only for the clock..
and now it permanently dissapears..
reinstalling the game essentials didn't work
how do I restore it back?
![image](https://github.com/mtricht/gamesense-essentials/assets/69665256/af262211-a4a1-478a-8c91-b681154ccd1e)

**Comment by mtricht** [comment]
I think the only way is to delete the app from inside the steelseries engine
