### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by lolrepeatlol** [mtricht/gamesense-essentials#9]
Thank you so much for your hard work on this! Is it possible to make this work for macOS?

**Comment by mtricht** [comment]
This will require some rewriting, but guess what? Coincidentally I'm getting a macbook pro tomorrow, so I'll actually be able to do this!

**Comment by lolrepeatlol** [comment]
Nice, thank you so much!

**Comment by mtricht** [comment]
@lolrepeatlol You can now download an experimental build for macOS

**Comment by lolrepeatlol** [comment]
Thank you so much :)) I appreciate the work. Will do soon

**Comment by lolrepeatlol** [comment]
macOS says that the file is damaged and it doesn't let me start the application. I've tried downloading it twice.

**Comment by adamf59** [comment]
> macOS says that the file is damaged and it doesn't let me start the application. I've tried downloading it twice.

I am getting the same effect on my Macbook Pro.
