### ISSUE TITLE
Keyboard Issues

### ISSUE THREAD

**Issue by as6977** [mtricht/gamesense-essentials#91]
I'm facing an issue where this program seems to be rendering my keyboard completely non-functional, as well as the RGB itself glitching out. I've rigorously followed all troubleshooting procedures, such as uninstalling and reinstalling the SteelSeries RGB software, refreshing keyboard drivers, reinstalling Windows, and attempting to uninstall and reinstall the GameSense application. Additionally, I've initiated an RMA request and obtained a replacement keyboard, initially suspecting hardware as the cause of the issue. However, after setting up the new keyboard and installing the GameSense software, I'm encountering the same issues.

**Comment by mtricht** [comment]
Sorry to hear that you're having issues. Sadly this is not really something I can help you with.

You may also be confused with Steelseries GameSense (now named Steelseries GG)?
