### ISSUE TITLE
Use with other apps

### ISSUE THREAD

**Issue by RDevelops** [mtricht/gamesense-essentials#92]
I want to use gamesense-essentials in order to see time and playback information, however I also want to use System Monitor to see system info.

My issue is, whenever system information shows, gamesense-essentials instantly changes it to something else. I thought this would be something to do with tick rate, so I upped the tick rate however this did not fix it.

  Is it possible to have both apps collaborate? I'm using an apex pro TKL.

**Comment by mtricht** [comment]
I believe this is a limitation from the steelseries API/GG and not something I can work around
